AutomationManager/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AM_History;
using AutomationManager.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AutomationManager.Controllers
{
    public class DashboardController : Controller
    {
        JobHistoryManager _jhm = new JobHistoryManager();
        int _limit = 1000;
        // GET: Dashboard
        public ActionResult Index()
        {
            List<HistoryModel> allHistFromDB = _jhm.GetAllJobHistory();
            List<JobHistory> historyToDisplay = new List<JobHistory>();
            int counter = 0;
            foreach(HistoryModel hm in allHistFromDB)
            {
                if (counter==_limit) { break;  }
                if (hm.Error != null)
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, hm.Error));
                } else
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, null));
                }
                counter++;
                
            }
            //do something to get jobHistory
            return View(historyToDisplay);
        }

        // GET: SqlJobsDash
        public ActionResult SqlJobHistory()
        {
            List<HistoryModel> allHistFromDB = _jhm.GetJobHistoryForJobType("SQL");
            List<JobHistory> historyToDisplay = new List<JobHistory>();
            int counter = 0;
            foreach (HistoryModel hm in allHistFromDB)
            {
                if (counter == _limit) { break; }
                if (hm.Error != null)
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, hm.Error));
                }
                else
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, null));
                }
                counter++;

            }
            //do something to get jobHistory
            return View(historyToDisplay);
        }

        public ActionResult SqlJobHistoryForType(string type)
        {
            List<HistoryModel> allHistFromDB = _jhm.GetJobHistoryForJobType("SQL", type);
            List<JobHistory> historyToDisplay = new List<JobHistory>();
            int counter = 0;
            foreach (HistoryModel hm in allHistFromDB)
            {
                if (counter == _limit) { break; }
                if (hm.Error != null)
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, hm.Error));
                }
                else
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, null));
                }
                counter++;

            }
            //do something to get jobHistory
            return View("SqlJobHistory",historyToDisplay);
        }

        // GET: SqlJobsDash
        public ActionResult CustomJobHistory()
        {
            List<HistoryModel> allHistFromDB = _jhm.GetJobHistoryForJobType("Custom");
            List<JobHistory> historyToDisplay = new List<JobHistory>();
            int counter = 0;
            foreach (HistoryModel hm in allHistFromDB)
            {
                if (counter == _limit) { break; }
                if (hm.Error != null)
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, hm.Error));
                }
                else
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, null));
                }
                counter++;

            }
            //do something to get jobHistory
            return View(historyToDisplay);
        }

        public ActionResult CustomJobHistoryForType(string type)
        {
            List<HistoryModel> allHistFromDB = _jhm.GetJobHistoryForJobType("Custom", type);
            List<JobHistory> historyToDisplay = new List<JobHistory>();
            int counter = 0;
            foreach (HistoryModel hm in allHistFromDB)
            {
                if (counter == _limit) { break; }
                if (hm.Error != null)
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, hm.Error));
                }
                else
                {
                    historyToDisplay.Add(new JobHistory(hm.Id, hm.JobType, hm.JobName, hm.DateRan, hm.Status, null));
                }
                counter++;

            }
            //do something to get jobHistory
            return View("CustomJobHistory", historyToDisplay);
        }
        // GET: Dashboard/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dashboard/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dashboard/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomationManager/Controllers/WindowsTasksController.cs
using AutomationManager.Data;
using AutomationManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AM_TaskScheduler;
using Task = Microsoft.Win32.TaskScheduler.Task;
using System.IO;

namespace AutomationManager.Controllers
{
    public class WindowsTasksController : Controller
    {
        private readonly DatabaseContext _context;

        public WindowsTasksController(DatabaseContext context)
        {
            _context = context;
        }

        private string localIP = Utils.GetAllLocalIPv4(System.Net.NetworkInformation.NetworkInterfaceType.Ethernet).FirstOrDefault();
        private string _folderPath = "\\WAM\\Uploads\\";
        


        // GET: WindowsTasks from system task registration, not database
        public async Task<IActionResult> Index()
        {
            //todo: make this async
            AM_TaskScheduler.TaskSchedulerManager tm = new AM_TaskScheduler.TaskSchedulerManager();
            List<Task> tasks = tm.GetTasks();
            List<WindowsTasks> windowsTasks = new List<WindowsTasks>();
            foreach (var t in tasks)
            {
                WindowsTasks task = new WindowsTasks();
                task.Id = Guid.NewGuid(); //need to map this to something else from the task. look into docs
                task.Name = t.Name;
                task.Description = t.Definition.RegistrationInfo.Description;
                var triggerCount = t.Definition.Triggers.Count;
                if (triggerCount > 0)
                {
                    task.TriggerType = t.Definition.Triggers.First().TriggerType.ToString();
                    task.TriggerString = t.Definition.Triggers.First().Repetition.ToString(); //need to figure out what the trigger's schedule looks like and put it in here 
                    task.TriggerAction = t.Definition.Actions.First().ActionType.ToString();
                }
                
                task.LastRun = t.LastRunTime;
                task.CreatedByUser = t.Definition.RegistrationInfo.Author;
                windowsTasks.Add(task);
            }

            // return View(await _context.WindowsTasks.ToListAsync());
            return View(windowsTasks);

        }

        // GET: WindowsTasks/Details/5
        public async Task<IActionResult> Details(string id, bool substring)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                TaskSchedulerManager tsm = new TaskSchedulerManager();
                var t = tsm.GetTask(id,substring);
                WindowsTasks task = new WindowsTasks();
                task.Id = Guid.NewGuid(); //need to map this to something else from the task. look into docs
                task.Name = t.Name;
                task.Description = t.Definition.RegistrationInfo.Description;
                var triggerCount = t.Definition.Triggers.Count;
                if (triggerCount > 0)
                {
                    task.TriggerType = t.Definition.Triggers.First().TriggerType.ToString();
                    //task.TriggerString = t.Definition.Triggers.First().Repetition.ToString(); //need to figure out what the trigger's schedule looks like and put it in here 
                    task.TriggerString = t.Definition.Triggers.First().ToString();
                    task.TriggerAction = t.Definition.Actions.First().ActionType.ToString();
                    task.ActionFilePath = t.Definition.Actions.First().ToString();
                }
                task.LastRun = t.LastRunTime;
                task.CreatedByUser = t.Definition.RegistrationInfo.Author;
                return View(task);
            } catch (Exception ex)
            {
                throw new Exception($"Failed to retreive task: {id}. Error: {ex.Message}");
            }

            
        }

        // GET: WindowsTasks/Create
        public IActionResult Create()
        {
            WindowsTasks task = new WindowsTasks();

            return View(task);
        }

        // POST: WindowsTasks/Create but not to database
        public IActionResult CreateTask(WindowsTasks task)
        {
            if (task.ActionFile.Length > 0)
            {
                // string filePath = $@"\\{localIP}\c$" + _folderPath;
                string filePath = "C:\\WAM\\Uploads\\"+task.ActionFile.FileName;
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    task.ActionFile.CopyToAsync(stream);
                    task.ActionFilePath = $@"\\{localIP}"+_folderPath + task.ActionFile.FileName;
                       

                }
            }
            //string server, string username, string domain, string password, string folder, string description, string cronString
            AM_TaskScheduler.TaskSchedulerManager tm = new AM_TaskScheduler.TaskSchedulerManager();
            WindowsTask mTasks = new WindowsTask(task);

            tm.CreateTask(mTasks);

            
            return RedirectToAction("Index");
        }

        // POST: WindowsTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,TriggerType,TriggerString,TriggerAction,DateCreated,LastRun,CreatedByUser")] WindowsTasks windowsTasks)
        {
            if (ModelState.IsValid)
            {
                windowsTasks.Id = Guid.NewGuid();
                _context.Add(windowsTasks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(windowsTasks);
        }

        // GET: WindowsTasks/Edit/5
        public async Task<IActionResult> Edit(string id, bool substring)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                TaskSchedulerManager tsm = new TaskSchedulerManager();
                var t = tsm.GetTask(id, substring);
                WindowsTasks task = new WindowsTasks();
                task.Id = Guid.NewGuid(); //need to map this to something else from the task. look into docs
                task.Name = t.Name;
                task.Description = t.Definition.RegistrationInfo.Description;
                var triggerCount = t.Definition.Triggers.Count;
                if (triggerCount > 0)
                {
                    task.TriggerType = t.Definition.Triggers.First().TriggerType.ToString();
                    //task.TriggerString = t.Definition.Triggers.First().Repetition.ToString(); //need to figure out what the trigger's schedule looks like and put it in here 
                    task.TriggerString = t.Definition.Triggers.First().ToString();
                    task.TriggerAction = t.Definition.Actions.First().ActionType.ToString();
                    task.ActionFilePath = t.Definition.Actions.First().ToString();
                }
                task.LastRun = t.LastRunTime;
                task.CreatedByUser = t.Definition.RegistrationInfo.Author;
                return View(task);
            }
            catch (Exception ex)
            {
                throw new Exception($"Failed to retreive task: {id}. Error: {ex.Message}");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(WindowsTasks task)
        {
            if (task.ActionFile.Length > 0)
            {
                // string filePath = $@"\\{localIP}\c$" + _folderPath;
                string filePath = "C:\\WAM\\Uploads\\" + task.ActionFile.FileName;
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    task.ActionFile.CopyToAsync(stream);
                    task.ActionFilePath = $@"\\{localIP}" + _folderPath + task.ActionFile.FileName;


                }
            }
            //string server, string username, string domain, string password, string folder, string description, string cronString
            AM_TaskScheduler.TaskSchedulerManager tm = new AM_TaskScheduler.TaskSchedulerManager();
            WindowsTask mTasks = new WindowsTask(task);

            tm.UpdateTask(mTasks);         
            return RedirectToAction("Index");
        }
            // GET: WindowsTasks/Delete/5
            public async Task<IActionResult> Delete(string taskName)
        {
            if (taskName == null)
            {
                return NotFound();
            }

            //todo: make this async
            AM_TaskScheduler.TaskSchedulerManager tm = new AM_TaskScheduler.TaskSchedulerManager();
            tm.DeleteTask(taskName);
            return RedirectToAction(nameof(Index));
        }

        // POST: WindowsTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var windowsTasks = await _context.WindowsTasks.FindAsync(id);
            _context.WindowsTasks.Remove(windowsTasks);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult TriggerTask(string id, bool substring)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                //string server, string username, string domain, string password, string folder, string description, string cronString
                AM_TaskScheduler.TaskSchedulerManager tm = new AM_TaskScheduler.TaskSchedulerManager();
                tm.TriggerTask(id,substring);
            }

AutomationManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewData["Title"] - WAM</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jqCron.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/jqCron.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
    </environment>
</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WAM</a>
            </div>
            <div class="list-group list-group-flush">
                @*<a asp-area="" asp-controller="Home" asp-action="Index">Home</a>*@
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="WindowsTasks" asp-action="Index">Windows Tasks</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="SqlJobs" asp-action="Index">SQL Agent Jobs</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="CustomJobs" asp-action="Index">Custom Jobs</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                <
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            @*<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="WindowsTasks" asp-action="Index">Windows Tasks</a>
                                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="SqlJobs" asp-action="Index">SQL Agent Jobs</a>
                                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="CustomJobs" asp-action="Index">Custom Jobs</a>
                                <a class="list-group-item list-group-item-action bg-light"  asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</aclass="list-group-item>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>*@

            <partial name="_CookieConsentPartial" />

            <div id="body-content" class="container body-content">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; 2018 - WAM - <a asp-area="" asp-controller="Home" asp-action="About">About</a> - <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></p>
                    <p></p>
                </footer>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/jqCron.js" asp-append-version="true"></script>
    <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    <script src="~/js/jqCron.en.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">

    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>
    <script src="~/js/jqCron.js" asp-append-version="true"></script>
    <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    <script src="~/js/jqCron.en.js" asp-append-version="true"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
    @RenderSection("Scripts", required: false)
</body>

</html>@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
        <title>@ViewData["Title"] - WAM</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
            <link rel="stylesheet" href="~/css/jqCron.css" />
            <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
            <link rel="stylesheet" href="~/css/jqCron.css" />
            <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WAM
            </a>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                <li><a asp-area="" asp-controller="WindowsTasks" asp-action="Index">Windows Tasks</a></li>
                                <li><a asp-area="" asp-controller="SqlJobs" asp-action="Index">SQL Agent Jobs</a></li>
                                <li><a asp-area="" asp-controller="CustomJobs" asp-action="Index">Custom Jobs</a></li>
                                <li><a asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>

                                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                            </ul>
                        </div>
                    </div>
                </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - WAM</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/js/jqCron.js" asp-append-version="true"></script>
            <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
            <script src="~/js/jqCron.en.js" asp-append-version="true"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">

            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="~/js/jqCron.js" asp-append-version="true"></script>
            <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
            <script src="~/js/jqCron.en.js" asp-append-version="true"></script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>

    </html>*@